config/urls.py
from django.urls import include, path

urlpatterns = [
    path("", include("weather.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

weather/urls.py
from django.urls import path

from . import views

app_name = "weather"

urlpatterns = [
    path("", views.home, name="home"),
    path("index", views.index, name="index"),
]

weather/views.py
import os

import pytz
from dateutil import parser
from django.shortcuts import render

from config.settings import TIME_ZONE

from .weather import Weather


def home(request):
    return render(request, "pages/home.html")


def index(request):
    location = request.GET.get("location")
    api_key = os.getenv("api_key")
    weather = Weather(api_key, location).get_weather_data()
    air_quality = Weather(api_key).get_air_quality()
    taiwan_timezone = pytz.timezone(TIME_ZONE)
    reference_time = weather.reference_time(timeformat="iso")

    time = (
        parser.isoparse(reference_time)
        .astimezone(taiwan_timezone)
        .strftime("%Y-%m-%d %H:%M:%S")
    )
    status = weather.status
    detailed_status = weather.detailed_status
    temp_f = weather.temperature("fahrenheit")
    temp_c = weather.temperature("celsius")
    humidity = weather.humidity
    wind_miles_hour = weather.wind(unit="miles_hour")
    wind_knots = weather.wind(unit="knots")
    wind_beaufort = weather.wind(unit="beaufort")
    rain_1 = weather.rain.get("1h", 0)
    rain_3 = weather.rain.get("3h", 0)
    press_metric = weather.barometric_pressure()["press"]
    press_imperial = weather.barometric_pressure(unit="inHg")["press"]
    visibility_metric = weather.visibility()
    visibility_imperial = weather.visibility(unit="miles")
    sunrise = (
        weather.sunrise_time(timeformat="date")
        .astimezone(taiwan_timezone)
        .strftime("%Y-%m-%d %H:%M:%S")
    )
    sunset = (
        weather.sunset_time(timeformat="date")
        .astimezone(taiwan_timezone)
        .strftime("%Y-%m-%d %H:%M:%S")
    )

    content = {
        "location": location,
        "time": time,
        "status": status,
        "detailed_status": detailed_status,
        "temp_f": temp_f,
        "temp_c": temp_c,
        "humidity": humidity,
        "wind_miles_hour": wind_miles_hour,
        "wind_knots": wind_knots,
        "wind_beaufort": wind_beaufort,
        "rain_1": rain_1,
        "rain_3": rain_3,
        "press_metric": press_metric,
        "press_imperial": press_imperial,
        "visibility_metric": visibility_metric,
        "visibility_imperial": visibility_imperial,
        "sunrise": sunrise,
        "sunset": sunset,
        "air_quality": air_quality,
    }
    return render(request, "pages/index.html", content)

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Weather</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!-- <script type="module" src="../static/script/app.js"></script> -->
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"
    ></script>
    <script
      src="https://kit.fontawesome.com/9cb8fe1d61.js"
      crossorigin="anonymous"
    ></script>
    {% tailwind_css %}
  </head>

  <body class="bg-gray-50 font-serif leading-normal tracking-normal">
    <div class="container mx-auto">
      <div class="flex justify-center items-center relative top-10">
        {% include "pages/home.html" %}
      </div>
      <section class="flex items-center justify-center h-screen">
        {% block content %} {% endblock %}
      </section>
    </div>
  </body>
</html>

weather/templates/pages/home.html
<section
  x-data="{ selectedLocation: localStorage.getItem('selectedLocation') || '' }"
>
  <form
    action="{% url 'weather:index' %}"
    @submit="localStorage.setItem('selectedLocation', selectedLocation)"
    class="flex join"
  >
    <label class="form-control max-w-xs join-item">
      <select
        x-model="selectedLocation"
        name="location"
        class="select select-secondary w-full max-w-xs join-item"
      >
        <option disabled>選擇地點</option>
        <option value="Keelung">基隆市</option>
        <option value="New Taipei City">新北市</option>
        <option value="Taipei City">台北市</option>
        <option value="Hsinchu County">新竹縣</option>
        <option value="Hsinchu">新竹市</option>
        <option value="Miaoli">苗栗縣市</option>
        <option value="Taichung">台中市</option>
        <option value="Changhua">彰化縣市</option>
        <option value="Nantou">南投縣市</option>
        <option value="Yunlin County">雲林縣</option>
        <option value="Chiayi">嘉義縣市</option>
        <option value="Tainan City">台南市</option>
        <option value="Kaohsiung City">高雄市</option>
        <option value="Pingtung">屏東縣市</option>
        <option value="Yilan">宜蘭縣市</option>
        <option value="Hualien">花蓮縣市</option>
        <option value="Taitung">台東縣市</option>
        <option value="Penghu County">澎湖縣</option>
        <option value="Green Island">綠島</option>
        <option value="Orchid Island">蘭嶼</option>
        <option value="Penghu County">金門縣</option>
        <option value="Matsu">馬祖</option>
        <option value="Lienchiang County">連江縣</option>
      </select>
    </label>
    <button
      type="submit"
      class="btn btn-ghost join-item"
      style="
        border-color: var(
          --fallback-s,
          oklch(var(--s) / var(--tw-border-opacity))
        );
      "
    >
      送出
    </button>
  </form>
</section>

weather/templates/pages/index.html
{% extends "base.html" %}{% block content %} {% load i18n %}
<section>
  <div>
    <p class="mb-3">現在時間：{% now "Y-m-d H:i" %}</p>
    <p class="mb-3">資料取得時間：{{time}}</p>
    <div class="stats shadow">
      <div class="stat grid grid-cols-2 gap-2">
        <div class="stat-figure text-primary w-8">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512">
            <path
              d="M160 64c-26.5 0-48 21.5-48 48l0 164.5c0 17.3-7.1 31.9-15.3 42.5C86.2 332.6 80 349.5 80 368c0 44.2 35.8 80 80 80s80-35.8 80-80c0-18.5-6.2-35.4-16.7-48.9c-8.2-10.6-15.3-25.2-15.3-42.5L208 112c0-26.5-21.5-48-48-48zM48 112C48 50.2 98.1 0 160 0s112 50.1 112 112l0 164.4c0 .1 .1 .3 .2 .6c.2 .6 .8 1.6 1.7 2.8c18.9 24.4 30.1 55 30.1 88.1c0 79.5-64.5 144-144 144S16 447.5 16 368c0-33.2 11.2-63.8 30.1-88.1c.9-1.2 1.5-2.2 1.7-2.8c.1-.3 .2-.5 .2-.6L48 112zM208 368c0 26.5-21.5 48-48 48s-48-21.5-48-48c0-20.9 13.4-38.7 32-45.3L144 144c0-8.8 7.2-16 16-16s16 7.2 16 16l0 178.7c18.6 6.6 32 24.4 32 45.3z"
            />
          </svg>
        </div>
        <div class="stat-title text-2xl">{{location}}</div>
        <div class="stat-value text-primary col-span-2">
          溫度：{{temp_c.temp}}℃
        </div>
        <div class="text-gray-400 text-sm">最高溫度：{{temp_c.temp_max}}℃</div>
        <div class="text-gray-400 text-sm">最低溫度：{{temp_c.temp_min}}℃</div>
        <div class="text-gray-400 text-sm">
          體感溫度：{{temp_c.feels_like}}℃
        </div>
        <div class="text-gray-400 text-sm">濕度：{{humidity}}%</div>
      </div>

      <div class="stat grid grid-cols-2 gap-2">
        <div class="stat-figure text-secondary w-12 m-2">
          {% if status == "Rain" %}
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
            <path
              d="M96 320c-53 0-96-43-96-96c0-42.5 27.6-78.6 65.9-91.2C64.7 126.1 64 119.1 64 112C64 50.1 114.1 0 176 0c43.1 0 80.5 24.3 99.2 60c14.7-17.1 36.5-28 60.8-28c44.2 0 80 35.8 80 80c0 5.5-.6 10.8-1.6 16c.5 0 1.1 0 1.6 0c53 0 96 43 96 96s-43 96-96 96L96 320zM81.5 353.9c12.2 5.2 17.8 19.3 12.6 31.5l-48 112c-5.2 12.2-19.3 17.8-31.5 12.6S-3.3 490.7 1.9 478.5l48-112c5.2-12.2 19.3-17.8 31.5-12.6zm120 0c12.2 5.2 17.8 19.3 12.6 31.5l-48 112c-5.2 12.2-19.3 17.8-31.5 12.6s-17.8-19.3-12.6-31.5l48-112c5.2-12.2 19.3-17.8 31.5-12.6zm244.6 31.5l-48 112c-5.2 12.2-19.3 17.8-31.5 12.6s-17.8-19.3-12.6-31.5l48-112c5.2-12.2 19.3-17.8 31.5-12.6s17.8 19.3 12.6 31.5zM313.5 353.9c12.2 5.2 17.8 19.3 12.6 31.5l-48 112c-5.2 12.2-19.3 17.8-31.5 12.6s-17.8-19.3-12.6-31.5l48-112c5.2-12.2 19.3-17.8 31.5-12.6z"
            />
          </svg>
          {% elif status == "Clouds" %}
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512">
            <path
              d="M0 336c0 79.5 64.5 144 144 144l368 0c70.7 0 128-57.3 128-128c0-61.9-44-113.6-102.4-125.4c4.1-10.7 6.4-22.4 6.4-34.6c0-53-43-96-96-96c-19.7 0-38.1 6-53.3 16.2C367 64.2 315.3 32 256 32C167.6 32 96 103.6 96 192c0 2.7 .1 5.4 .2 8.1C40.2 219.8 0 273.2 0 336z"
            />
          </svg>
          {% elif status == "drizzle" %}
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
            <path
              d="M96 320c-53 0-96-43-96-96c0-42.5 27.6-78.6 65.9-91.2C64.7 126.1 64 119.1 64 112C64 50.1 114.1 0 176 0c43.1 0 80.5 24.3 99.2 60c14.7-17.1 36.5-28 60.8-28c44.2 0 80 35.8 80 80c0 5.5-.6 10.8-1.6 16c.5 0 1.1 0 1.6 0c53 0 96 43 96 96s-43 96-96 96L96 320zm-6.8 52c1.3-2.5 3.9-4 6.8-4s5.4 1.5 6.8 4l35.1 64.6c4.1 7.5 6.2 15.8 6.2 24.3l0 3c0 26.5-21.5 48-48 48s-48-21.5-48-48l0-3c0-8.5 2.1-16.9 6.2-24.3L89.2 372zm160 0c1.3-2.5 3.9-4 6.8-4s5.4 1.5 6.8 4l35.1 64.6c4.1 7.5 6.2 15.8 6.2 24.3l0 3c0 26.5-21.5 48-48 48s-48-21.5-48-48l0-3c0-8.5 2.1-16.9 6.2-24.3L249.2 372zm124.9 64.6L409.2 372c1.3-2.5 3.9-4 6.8-4s5.4 1.5 6.8 4l35.1 64.6c4.1 7.5 6.2 15.8 6.2 24.3l0 3c0 26.5-21.5 48-48 48s-48-21.5-48-48l0-3c0-8.5 2.1-16.9 6.2-24.3z"
            />
          </svg>
          {% endif %}
        </div>
        <div class="stat-title text-2xl">天氣</div>
        <div class="stat-value text-secondary col-span-2">{{status}}</div>
        <div class="text-gray-400 text-sm col-span-2">{{detailed_status}}</div>
        <div class="text-gray-400 text-sm">最近一小時降雨量：{{rain_1}}</div>
        <div class="text-gray-400 text-sm">最近三小時降雨量：{{rain_3}}</div>
      </div>

      <div class="stat">
        <div class="stat-value">
          <p class="mb-3">風速：{{wind_miles_hour.speed|floatformat:2}} m/s</p>
          <p class="mb-4">風向：
          {% if wind_miles_hour.deg > 348.75 and wind_miles_hour.deg < 11.25 %}
          北
          {% elif wind_miles_hour.deg > 11.26 and wind_miles_hour.deg < 33.75 %}
          北東北
          {% elif wind_miles_hour.deg > 33.76 and wind_miles_hour.deg < 56.25 %}
          東北
          {% elif wind_miles_hour.deg > 56.26 and wind_miles_hour.deg < 78.75 %}
          東東北
          {% elif wind_miles_hour.deg > 78.76 and wind_miles_hour.deg < 101.25 %}
          東
          {% elif wind_miles_hour.deg > 101.26 and wind_miles_hour.deg < 123.75 %}
          東東南
          {% elif wind_miles_hour.deg > 123.76 and wind_miles_hour.deg < 146.25 %}
          東南
          {% elif wind_miles_hour.deg > 146.26 and wind_miles_hour.deg < 168.75 %}
          南東南
          {% elif wind_miles_hour.deg > 168.76 and wind_miles_hour.deg < 191.25 %}
          南
          {% elif wind_miles_hour.deg > 191.26 and wind_miles_hour.deg < 213.75 %}
          南西南
          {% elif wind_miles_hour.deg > 213.76 and wind_miles_hour.deg < 236.25 %}
          西南
          {% elif wind_miles_hour.deg > 236.26 and wind_miles_hour.deg < 258.75 %}
          西西南
          {% elif wind_miles_hour.deg > 258.76 and wind_miles_hour.deg < 281.25 %}
          西
          {% elif wind_miles_hour.deg > 281.26 and wind_miles_hour.deg < 303.75 %}
          西西北
          {% elif wind_miles_hour.deg > 303.76 and wind_miles_hour.deg < 326.25 %}
          西北
          {% elif wind_miles_hour.deg > 326.26 and wind_miles_hour.deg < 348.75 %}
          北西北
          {% endif %}
          </p>
        </div>
        <div class="text-gray-400 text-sm">日出時間：{{sunrise}}</div>
        <div class="text-gray-400 text-sm">日落時間：{{sunset}}</div>
      </div>
    </div>
  </div>
</section>
{% comment %}
<p>溫度：{{temp_f.temp}}℉</p>
<p>最高溫度：{{temp_f.temp_max}}℉</p>
<p>最低溫度：{{temp_f.temp_min}}℉</p>
<p>體感溫度：{{temp_f.feels_like}}℉</p>

<p>溫度：{{temp_c.temp}}℃</p>
<p>最高溫度：{{temp_c.temp_max}}℃</p>
<p>最低溫度：{{temp_c.temp_min}}℃</p>
<p>體感溫度：{{temp_c.feels_like}}℃</p>
<p>濕度：{{humidity}}%</p>

<p>風速：{{wind_miles_hour.speed|floatformat:2}}meter/sec</p>
<p>風向：{{wind_miles_hour.deg}}deg</p>
<p>陣風：{{wind_miles_hour.gust|floatformat:2}}meter/sec</p>
<p>風速：{{wind_knots.speed|floatformat:2}}meter/sec</p>
<p>風向：{{wind_knots.deg}}deg</p>
<p>陣風：{{wind_knots.gust|floatformat:2}}meter/sec</p>
<p>蒲氏風級：{{wind_beaufort.speed|floatformat:2}}meter/sec</p>
<p>蒲氏風級：{{wind_beaufort.deg}}deg</p>
<p>蒲氏風級：{{wind_beaufort.gust|floatformat:2}}meter/sec</p>

<p>最近一小時降雨量：{{rain_1}}</p>
<p>最近三小時降雨量：{{rain_3}}</p>
<p>大氣壓力：{{press_metric}}KPa</p>
<p>大氣壓力：{{press_imperial}}inHg</p>
<p>可見度：{{visibility_metric}}</p>
<p>可見度：{{visibility_imperial}}</p>
<p>日出時間：{{sunrise}}</p>
<p>日落時間：{{sunset}}</p>
{% endcomment %} {% endblock %}